"""empty message

Revision ID: 104768ff28e7
Revises: df0b473c9b87
Create Date: 2019-12-05 15:18:41.880548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104768ff28e7'
down_revision = 'df0b473c9b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isAdmin')
    # ### end Alembic commands ###
