"""empty message

Revision ID: b12eb78447a0
Revises: 6f1303da1888
Create Date: 2019-11-27 17:33:54.209837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12eb78447a0'
down_revision = '6f1303da1888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_name', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'user', ['user_name'], ['username'])
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'user', ['user_id'], ['id'])
    op.drop_column('orders', 'user_name')
    # ### end Alembic commands ###
